name: 'kubernetes-bom-installer'
description: 'Install the Kubernetes bom tool to generate the SBOM file using SPDX format'
branding:
  icon: 'package'
  color: 'blue'
inputs:
  version:
    description: 'Kubernetes bom command version to be installed'
    required: false
    default: v0.3.0
  arch:
    description: 'Kubernetes bom command arch to be installed'
    required: false
    default: "linux-amd64"
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        #!/bin/bash
        set -e

        INSTALL_DIR=$HOME/.bom-generator
        mkdir -p $INSTALL_DIR

        curl -L -O https://github.com/kubernetes-sigs/bom/releases/download/${{ inputs.version }}/bom-${{ inputs.arch }}.tar.gz
        tar -xf bom-${{ inputs.arch }}.tar.gz --directory $INSTALL_DIR

        echo $INSTALL_DIR >> $GITHUB_PATH
