name: 'kubewarden-policy-build-rust'
description: 'Build a rust policy using rust'
branding:
  icon: 'package'
  color: 'blue'
runs:
  using: "composite"
  steps:
    -
      name: Checkout code
      uses: actions/checkout@v3
    -
      name: Prepare Rust environment
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: wasm32-wasi
    -
      name: Build Wasm module
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --target=wasm32-wasi --release
    -
      name: Rename Wasm module
      shell: bash
      run: |
        cp target/wasm32-wasi/release/*.wasm policy.wasm
    -
      name: Annotate Wasm module
      shell: bash
      run: |
        make annotated-policy.wasm
    -
      name: Generate the SBOM files
      shell: bash
      run: |
        spdx-sbom-generator -f json

        # SBOM files should have "sbom" in the name due the CLO monitor
        # https://clomonitor.io/docs/topics/checks/#software-bill-of-materials-sbom
        mv bom-cargo.json policy-sbom.spdx.json
    -
      name: Sign BOM file
      shell: bash
      run: |
        cosign sign-blob --yes --output-certificate policy-sbom.spdx.cert \
          --output-signature policy-sbom.spdx.sig \
          policy-sbom.spdx.json
    -
      name:  Upload policy SBOM files
      uses: actions/upload-artifact@v3
      with:
        name: policy-sbom
        path: |
          policy-sbom.spdx.json
          policy-sbom.spdx.cert
          policy-sbom.spdx.sig
