name: 'syft-installer'
description: 'Install syft and includes it inside of PATH'
branding:
  icon: 'package'
  color: 'blue'
inputs:
  VERSION:
    description: 'syft release to be installed'
    required: false
    default: "0.85.0"
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        #!/bin/bash
        set -e

        INSTALL_DIR=$HOME/.syft

        mkdir -p $INSTALL_DIR

        curl -sL https://github.com/anchore/syft/releases/download/v${{ inputs.VERSION }}/syft_${{ inputs.VERSION }}_linux_amd64.tar.gz -o $INSTALL_DIR/syft.tar.gz
        tar xvf $INSTALL_DIR/syft.tar.gz -C $INSTALL_DIR
        rm $INSTALL_DIR/syft.tar.gz

        echo $INSTALL_DIR >> $GITHUB_PATH

