name: Tests and linters

on:
  workflow_call:
    inputs: {}
    secrets: {}

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 14
    steps:
      -
        uses: actions/checkout@v3
      -
        name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '${{ env.NODE_VERSION }}'
      -
        name: Install npm
        run: npm install
      -
        name: Run unit-tests
        run: |
          make test
