name: Tests and linters

on:
  workflow_call:
    secrets: {}

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run tests
        uses: swiftwasm/swiftwasm-action@5f4ac6cd6d2273f0c6aba57d7281736428f0aeb7 # v5.9
        with:
          shell-action: carton test
