name: Tests and linters

on:
  workflow_call:
    secrets: {}

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: setup Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5
        with:
          go-version: "1.24"

      - name: run Go unit tests
        run: make test

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install dependencies
        uses: kubewarden/github-actions/policy-gh-action-dependencies@v4.3.0
      - name: Build and annotate policy
        with:
          generate-sbom: false
        uses: kubewarden/github-actions/policy-build-tinygo@v4.3.0
      - name: Run e2e tests
        run: make e2e-tests

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5
        with:
          go-version: "1.24"
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@4696ba8babb6127d732c3c6dde519db15edab9ea # v6.5.1
        with:
          version: "latest"
